### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by Shiaulis** [OpenCovidTrace/octrace-ios#17]
Did you consider SPM as your dependency manager? Looks like all dependencies you are using right now are SPM ready
![image](https://user-images.githubusercontent.com/13601748/82943700-b5b0c280-9fa2-11ea-95ed-866e6a2f06fd.png)

The only issue with Firebase, but I don't see any usage of it. Or do you have plans to use it as well?

**Comment by alexnivanov** [comment]
We use Firebase for Analytics and Crashlytics. They are working out of the box.
