### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by Shiaulis** [OpenCovidTrace/octrace-ios#9]
Did you consider some online CI setup for the project? For example, Bitrise can be used for that. It is free with some limitations
https://www.bitrise.io
I partially can do some setup, but it is needed admin privileges from repository owner so part of actions needed from the owners side

**Comment by alexnivanov** [comment]
Thanks for the info, need to take a look...

**Comment by alexnivanov** [comment]
Issue reported by Bitrise when configuring project:

```
No shared schemes found for project: octrace.xcworkspace.
Automatically generated schemes may differ from the ones in your project.
Make sure to share your schemes for the expected behaviour.
```

However, in Xcode everything seems to be OK:
![image](https://user-images.githubusercontent.com/13519834/82646057-902b5e00-9c1c-11ea-92eb-8d68019d079d.png)

**Comment by Shiaulis** [comment]
Yes, I had this issue and created scheme by myself. Let me try to fix it

**Comment by alexnivanov** [comment]
After going into settings I noticed that the shared scheme file actually appeared. Pushed it and now everything works fine!

**Comment by alexnivanov** [comment]
Now Bitrise workflow fails on _Xcode Archive & Export for iOS_ step: need to setup code signing.
@Shiaulis, don't you know if we can just build the project and check for warnings instead? No need for exporting and setting up code signing for now...

**Comment by Shiaulis** [comment]
Can you add me to the project in Bitrise with limited access to it so I can check later today? shiaulis@gmail.com

**Comment by alexnivanov** [comment]
Yup, invited with temporary admin access so that you'd be able to edit workflows!

**Comment by Shiaulis** [comment]
Can you please enable this from Bitrise settings?
![image](https://user-images.githubusercontent.com/13601748/82692558-9b0be000-9c68-11ea-8c70-c9053cf8ccc0.png)

**Comment by alexnivanov** [comment]
@Shiaulis done!

**Comment by Shiaulis** [comment]
Can you also check webhook? it looks like for some reason it stopped working 
![image](https://user-images.githubusercontent.com/13601748/82804540-249af800-9e8b-11ea-9b49-01d9069183ef.png) It is in project `CODE` tab

**Comment by Shiaulis** [comment]
I am hoping to see the checkmark for each PR in the app whether it is failed or succeeded

**Comment by alexnivanov** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/13519834/82804974-e5b97200-9e8b-11ea-9230-c73fbcc2c095.png">

I checked the web hook, and it's there. Seems to be some Bitrise issue...

**Comment by Shiaulis** [comment]
I created a new one and looks like it works:
![image](https://user-images.githubusercontent.com/13601748/82805165-3af58380-9e8c-11ea-8b92-a598b6638b63.png)
